### ISSUE TITLE
Cannot find module 'handlebars'

### ISSUE THREAD

**Issue by joanniclaborde** [blocks/alerter#7]
Handlebars is specified in the `devDependencies`. It should be added in the `dependencies` instead. But doing this means it needs to be added in all modules like alerter, or it can also only be installed once in the parent package. I'm not sure which solution is best?

**Comment by josiahsprague** [comment]
Hmm, I think this original decision had something to do with file size of the bundled module, and avoiding having multiple instances of Handlebars. When this module is included as a dependency in a parent project, it should be using pre-compiled handlebars templates and ∴ only the runtime should be a dependency. If a custom template is being used the parent project should require Handlebars as a dependency in the parent. I'll look into this again. What project are you running into issues on @joanniclaborde?

**Comment by joanniclaborde** [comment]
Been reading on `peerDependencies` a little bit, and this could be the solution. Adding `handlebars` (and even `hbsfy`) to `peerDependencies` will only install them in the parent project once, shared by all dependencies, instead of installing it in each dependency's local `node_modules`.

**Comment by josiahsprague** [comment]
Actually, I was thinking since adding it to dependencies doesn't add anything else to the bundle on the front end, it doesn't really matter. I'm going to push a patch that fixes the dependencies list for this and subscribe-email.

**Comment by joanniclaborde** [comment]
The only downside to this is that handlebars and hbsfy are installed for both packages when you use alerter and subscribe-email, it's just longer to install / deploy everything.

**Comment by pushred** [comment]
Yeah.. what happens when we have 20 of these in a project? It's 1.2mb per instance as of 1.3.0 and 2.3mb at 3.0.0. Broadway gives us a preview, it already weighs in at 56mb with a healthy contribution from qa-deployer — 20mb(!) and modulus-cli — 15mb(!)

In short, this is nothing new?

`peerDependencies` makes sense in that it kind of makes sense to only have one version of Handlebars in play per project. I question how realistic this is. Are we really going to keep everything up-to-date, or be stuck at an old version periodically until we can get around to that? There's been [so much debate][1] over the feature and it's still not documented in the new npm site. It really feels like it could disappear at any moment. The experience of others is definitely some indication we'd just be kicking our dependency problems down the road.

The dependency error is due to the hbsfy transform in the package right? That ended up here because we wanted to keep the frontend build light, and that's really the foremost goal. We make the parent project responsible for the build and preserve all the requires leading up to it, rather than compiling each in advance and bringing along redundant copies of the runtime, etc. along.

There could be a way to address the issue in hbsfy, but the current approach may well be the best, all things considered. It allows each block to define their own specific dependencies, even if it's bit wasteful at times to setup a dev environment.

[1]: https://github.com/npm/npm/issues/5080#issuecomment-40545599

**Comment by pushred** [comment]
Another thought: if the specified versions for a set of block are more or less agreeable, doesn't the npm cache mitigate the file size? If you needed to deploy the modules you could also run [`dedupe`](https://docs.npmjs.com/cli/dedupe) before hand to minimize that?

**Comment by josiahsprague** [comment]
I think `peerDependencies` is more for packages that are optional and for locking those at a specific version. Since Handlebars/hbsfy aren't optional in this case, I think it makes sense to have them in `dependencies`. It doesn't change the front end build size, and I think the only place where large `node_modules` folders has been getting in our way is with Modulus deploys. Other than that, `npm install` happens infrequently enough that I don't think it's really tedious to work with the file sizes we're talking about. But even so, we could definitely reduce some of that by adding an `npm dedupe` command to our deploy/vagrant scripts.
